import './globals.css'
import localFont from 'next/font/local'
import { Providers } from './providers'
const myFont = localFont({ src: '../fonts/Roboto-Regular.ttf' })

export const metadata = {
  title: 'FReyeSFT portafolio',
  description: 'Generated by create next app'
}

export default function RootLayout ({ children }) {
  return (
    <html className='bg-[#f0f0f0]' lang='en'>
      <body className={`${myFont.className}`}>
        <Providers>
          {children}
        </Providers>
      </body>
    </html>
  )
}
